### ISSUE TITLE
Add Grand Finale

### ISSUE THREAD

**Issue by dboone** [tedmiston/qcbrunch#4]
Grand Finale
3 E Sharon Rd, Cincinnati, OH 45246
Sunday Brunch
10:30 - 14:30
http://www.grandfinale.info/

**Comment by tedmiston** [comment]
Thanks, Derek!  I'll get this up tonight.  :)

**Comment by dboone** [comment]
Very nice, Taylor! I like the site.

Hope you are doing well!

**Comment by tedmiston** [comment]
Thank you, it's been a fun little mini side project so far.

Let me know next time you're around OTR / downtown and we can grab a coffee or something.
