### ISSUE TITLE
Add Log Cabin Inn

### ISSUE THREAD

**Issue by tedmiston** [tedmiston/qcbrunch#8]

**Comment by ElegantRabbit** [comment]
Saturday Brunch (TripAdvisor says they open at 8pm on Saturday, might be a typo, will confirm but they don't have any online presence)

Sunday Brunch: 8am - ?

Menu: https://www.zomato.com/cincinnati/log-cabin-inn-covington/menu#tabtop

Toast Bar: No

Notes: None
